version: '3.9'

services:
  db:
    image: postgres
    container_name: socialnetwork_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: socialnetwork
    ports:
      - "5432:5432"
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data 

  pgadmin:
    container_name: socialnetwork_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"